import { supabase } from '@/integrations/supabase/client';

export interface SitemapEntry {
  url: string;
  lastModified?: Date;
  changeFrequency?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: number;
}

/**
 * Generate XML sitemap from database entries
 */
export async function generateSitemap(): Promise<string> {
  const baseUrl = import.meta.env.VITE_APP_URL || 'https://vaultverse.com';

  // Fetch all enabled sitemap entries
  const { data: entries, error } = await supabase
    .from('sitemap_entries')
    .select('*')
    .eq('enabled', true)
    .order('priority', { ascending: false });

  if (error) {
    console.error('Error fetching sitemap entries:', error);
    return generateDefaultSitemap(baseUrl);
  }

  const sitemapEntries: SitemapEntry[] = entries?.map(entry => ({
    url: entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`,
    lastModified: new Date(entry.last_modified),
    changeFrequency: entry.change_frequency as any,
    priority: Number(entry.priority),
  })) || [];

  return buildXML(sitemapEntries);
}

/**
 * Build XML string from sitemap entries
 */
function buildXML(entries: SitemapEntry[]): string {
  const urls = entries.map(entry => {
    const lastmod = entry.lastModified
      ? `  <lastmod>${entry.lastModified.toISOString().split('T')[0]}</lastmod>\n`
      : '';
    const changefreq = entry.changeFrequency
      ? `  <changefreq>${entry.changeFrequency}</changefreq>\n`
      : '';
    const priority = entry.priority !== undefined
      ? `  <priority>${entry.priority.toFixed(1)}</priority>\n`
      : '';

    return `<url>\n  <loc>${escapeXML(entry.url)}</loc>\n${lastmod}${changefreq}${priority}</url>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

/**
 * Generate default sitemap if database is unavailable
 */
function generateDefaultSitemap(baseUrl: string): string {
  const defaultEntries: SitemapEntry[] = [
    { url: `${baseUrl}/`, priority: 1.0, changeFrequency: 'weekly' },
    { url: `${baseUrl}/features`, priority: 0.8, changeFrequency: 'monthly' },
    { url: `${baseUrl}/pricing`, priority: 0.8, changeFrequency: 'monthly' },
    { url: `${baseUrl}/docs`, priority: 0.9, changeFrequency: 'weekly' },
  ];

  return buildXML(defaultEntries);
}

/**
 * Escape special XML characters
 */
function escapeXML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Fetch and cache sitemap (useful for static generation)
 */
export async function getSitemapXML(): Promise<string> {
  try {
    return await generateSitemap();
  } catch (error) {
    console.error('Error generating sitemap:', error);
    const baseUrl = import.meta.env.VITE_APP_URL || 'https://vaultverse.com';
    return generateDefaultSitemap(baseUrl);
  }
}

/**
 * Add or update a sitemap entry
 */
export async function addSitemapEntry(entry: {
  url: string;
  priority?: number;
  changeFrequency?: string;
  autoGenerated?: boolean;
}) {
  const { error } = await supabase
    .from('sitemap_entries')
    .upsert({
      url: entry.url,
      priority: entry.priority || 0.5,
      change_frequency: entry.changeFrequency || 'weekly',
      auto_generated: entry.autoGenerated || false,
      last_modified: new Date().toISOString(),
    });

  if (error) {
    console.error('Error adding sitemap entry:', error);
    throw error;
  }
}

/**
 * Remove a sitemap entry
 */
export async function removeSitemapEntry(url: string) {
  const { error } = await supabase
    .from('sitemap_entries')
    .delete()
    .eq('url', url);

  if (error) {
    console.error('Error removing sitemap entry:', error);
    throw error;
  }
}
